# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XNxzIq6CyDSDhbZ9a3BdK7T10eGReAbH
"""

pip install transformers

from transformers import pipeline

import pandas as pd

data = pd.read_html('https://en.wikipedia.org/wiki/National_Institutes_of_Technology_(India)',header=0)

data[2]

from transformers import AutoTokenizer, AutoModelForDocumentQuestionAnswering,Pipeline

model="google/tapas-base-finetuned-wtq"

tokenizer = AutoTokenizer.from_pretrained(model)

data=data.astype(str)

table_qa_pipeline = pipeline("table-question-answering", model=model, tokenizer=tokenizer)

result = table_qa_pipeline(table=data, query="who is younger?")

pip install streamlit



!streamlit run Untitled2.ipynb

!jupyter nbconvert --to script your_notebook.ipynb

!streamlit run your_notebook.py

!jupyter nbconvert --to script my_table_qa.ipynb

